[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[dependencies]
matplotlib = "*"
imageio = "*"
ipykernel = "*"

[pypi-dependencies]
pyfragments.path = "."

[feature]
py39.dependencies.python = "3.9.*"
py310.dependencies.python = "3.10.*"
py311.dependencies.python = "3.11.*"
py312.dependencies.python = "3.12.*"
py313.dependencies.python = "3.13.*"
py314.dependencies.python = "3.14.*"

[feature.quarto]
dependencies = {
  quarto = "*",
  pyyaml = "*",
  nbformat = "*",
  nbclient = "*",
}
tasks = {
  render = {
    cwd = "docs",
    cmd = "quarto render",
    inputs = ["src/", "docs/**/*.qmd", "docs/_quarto.yml"],
    outputs = ["docs/_site"],
  },
  publish = {
    cwd = "docs",
    cmd = "quarto publish gh-pages --no-prompt --no-render",
    depends-on = ["render"],
  }
}

[feature.lint]
dependencies = {
  prek = "*",
  tombi = "*",
  ruff = "*",
}
tasks = { lint = "prek --all-files" }

[feature.build]
dependencies = { uv = "*" }
tasks = {
  build = "uv build",
  _publish = "uv publish",
}

[feature.test]
dependencies = { pytest = "*" }
tasks = { test = "pytest --doctest-modules" }

[environments]
default = ["test", "py39", "lint", "build", "quarto"]
py310 = ["test", "py310"]
py311 = ["test", "py311"]
py312 = ["test", "py312"]
py313 = ["test", "py313"]
py314 = ["test", "py314"]
