[project]
name = "pyfragments"
version = "0.4.1"
description = "Add animations to revealjs presentations from Python code-blocks."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "Mauro Silberberg", email = "maurosilber@gmail.com" }]
keywords = [
  "animations",
  "fragments",
  "matplotlib",
  "presentation",
  "quarto",
  "revealjs",
]
classifiers = ["Programming Language :: Python :: 3"]
dependencies = ["ipykernel", "matplotlib"]
optional-dependencies = { "png" = ["imageio"] }

[project.urls]
Documentation = "https://maurosilber.github.io/pyfragments"
Homepage = "https://github.com/maurosilber/pyfragments"
Issues = "https://github.com/maurosilber/pyfragments/issues"

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
pythonpath = "."

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.tombi]
toml-version = "v1.1.0"
