project:
  type: website

website:
  title: "PyFragments examples"
  navbar:
    left:
      - examples/animated_png.qmd
      - examples/animated_svg.qmd

format:
  html:
    theme: cosmo
    toc: true
